### ISSUE TITLE
Add tags on GitHub for discoverability

### ISSUE THREAD

**Issue by timkpaine** [jpmorganchase/regular-table#16]
![Screen Shot 2020-05-25 at 12 44 00](https://user-images.githubusercontent.com/3105306/82831298-0f6f9a80-9e86-11ea-9932-7019db34b882.png)

**Comment by telamonian** [comment]
From the prior art in https://github.com/jpmorganchase/regular-table/issues/14#issue-623829822, here's some tags commonly used by projects playing in the same space:

scroller, listview, datagrid, datatable, grid

**Comment by timkpaine** [comment]
fixed
