### ISSUE TITLE
regular-table doesn't update on scroll in firefox

### ISSUE THREAD

**Issue by telamonian** [jpmorganchase/regular-table#26]
### Steps to Reproduce:

Open the [two billion rows example](https://bl.ocks.org/texodus/483a42e7b877043714e18bea6872b039) in a firefox browser, then scroll down and to the right a little

### Expected Result:

The same thing as on chrome:

![image](https://user-images.githubusercontent.com/2263641/83316945-3e27a100-a1f7-11ea-98b6-16baed4ea558.png)

### Actual Result:

The only thing that shows up is the initial table on load:

![image](https://user-images.githubusercontent.com/2263641/83316968-6a432200-a1f7-11ea-8513-6843f21cfc10.png)

### Environment:

OSX 10.14, firefox 77 and 78

### Additional Context:

NA

**Comment by texodus** [comment]
Thanks for the report and fix!
