### ISSUE TITLE
Reference: prior art

### ISSUE THREAD

**Issue by telamonian** [jpmorganchase/regular-table#3]
Links to prior art of virtualized tables, for reference:

curated lists of grid/table projects:
- [awesome-grid](https://github.com/FancyGrid/awesome-grid)

vanilla javascript + DOM (similar to this project):
- [Clusterize](https://github.com/NeXTs/Clusterize.js)

React-based:
- [react-table](https://github.com/tannerlinsley/react-table)
- [react-datasheet](https://github.com/nadbm/react-datasheet)
- [Griddle](https://github.com/GriddleGriddle/Griddle)
- [material-table](https://github.com/mbrn/material-table)
- [rsuite-table](https://github.com/rsuite/rsuite-table)
- frameworks:
  - [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc)
  - [react-virtualized](https://github.com/bvaughn/react-virtualized)

for Angular/Vue:
- [primeng](https://github.com/primefaces/primeng/tree/master/src/app/components/table)
- [ngx-datatable](https://github.com/swimlane/ngx-datatable) 

other:
- [jqGrid](https://github.com/tonytomov/jqGrid)
- [tabulator](https://github.com/olifolkerd/tabulator)
- [tui.grid](https://github.com/nhn/tui.grid)

**Comment by texodus** [comment]
Thanks for this!

If this isn't related to a specific issue, lets please keep discussion in another forum.
I'd like to keep [Issues](https://github.com/jpmorganchase/regular-table/issues) for issue reporting and specific user/developer help.
