### ISSUE TITLE
No license in bl.ocks examples

### ISSUE THREAD

**Issue by telamonian** [jpmorganchase/regular-table#30]
I was looking through the latest bl.ocks examples listed in the README, and I noticed this at the bottom:

![image](https://user-images.githubusercontent.com/2263641/83479214-eb9fec00-a465-11ea-9ef9-cb5d9dda6319.png)

The [bl.ocks instructions]() say to list a `license` field in a `.blocks` yaml file. @texodus I guess `.blocks` could be added to [`sync_gist`](https://github.com/jpmorganchase/regular-table/blob/master/scripts/sync_gist.js)?

**Comment by texodus** [comment]
Thanks for the report!
